server:
  port: 8888

app:
  api-prefix: /api

gateway:
  public-paths:
    - /api/identity/auth/login
    - /api/identity/auth/register
    - /api/identity/auth/introspect
    - /api/notification/email/send
    - /api/file/media/download

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity_service
              uri: http://localhost:8080
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                - StripPrefix=1
            - id: profile_service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/profile/users/**
              filters:
                - StripPrefix=1
            - id: notification_service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/notification/**
              filters:
                - StripPrefix=1
            - id: post_service
              uri: http://localhost:8083
              predicates:
                - Path=${app.api-prefix}/post/**
              filters:
                - StripPrefix=1
            - id: file_service
              uri: http://localhost:8084
              predicates:
                - Path=${app.api-prefix}/file/**
              filters:
                - StripPrefix=1